version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "prettier"